export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './Navbar.vue'
export { default as Sidebar } from './Sidebar/Index.vue'
export { default as TagsView } from './TagsView.vue'
export { default as Footer } from './Footer.vue'
